name: Build & Deploy Documentation on rs.delta.chat

on:
  push:
    branches:
      - master
      - docs-gh-action

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        cargo doc
    - name: Upload
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "delta.chat"
        port: 22
        local: "target/doc/"
        remote: "/var/www/html/rs/"

