# GitHub Actions workflow
# to build `deltachat_fii` crate documentation
# and upload it to <https://cffi.delta.chat/>

name: Build & Deploy Documentation on cffi.delta.chat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Build the documentation with cargo
        run: |
          cargo doc --package deltachat_ffi --no-deps
      - name: Upload to cffi.delta.chat
        uses: up9cloud/action-rsync@v1.3
        env:
          USER: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          HOST: "delta.chat"
          SOURCE: "target/doc"
          TARGET: "/var/www/html/cffi/"
