name: Build & Deploy Documentation on rs.delta.chat

on:
  push:
    branches:
      - master
      - docs-gh-action

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        cargo doc --package deltachat --no-deps
    - name: Upload
      uses: up9cloud/action-rsync@v1.3
      env:
        USER: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        HOST: "delta.chat"
        SOURCE: "target/doc"
        TARGET: "/var/www/html/rs/"

