name: Build & Deploy Documentation on py.delta.chat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0 # Fetch history to calculate VCS version number.
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Python documentation
        run: nix build .#python-docs
      - name: Upload to py.delta.chat
        uses: up9cloud/action-rsync@v1.3
        env:
          USER: delta
          KEY: ${{ secrets.CODESPEAK_KEY }}
          HOST: "lists.codespeak.net"
          SOURCE: "result/html/"
          TARGET: "/home/delta/build/master"
